SELECT 
    QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM (
    SELECT 
        CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q') AS QUARTER
    FROM 
        ECOLI_DATA
) AS TEMP
GROUP BY 
    QUARTER
ORDER BY 
    QUARTER;