-- 코드를 입력하세요
SELECT P.PRODUCT_CODE AS PRODUCT_CODE, sum(P.PRICE*O.SALES_AMOUNT) AS SALES FROM PRODUCT P
INNER JOIN OFFLINE_SALE O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC