WITH JULY_TOTAL AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_ORDER
    FROM JULY
    GROUP BY FLAVOR
),
ORDER_SUM AS (
    SELECT F.FLAVOR, F.TOTAL_ORDER + IFNULL(J.JULY_ORDER, 0) AS TOTAL_ORDER
    FROM FIRST_HALF F
    LEFT JOIN JULY_TOTAL J ON F.FLAVOR = J.FLAVOR
)
SELECT FLAVOR
FROM ORDER_SUM
ORDER BY TOTAL_ORDER DESC
LIMIT 3;