SELECT 
    E.EMP_NO, 
    E.EMP_NAME,
    CASE
        WHEN AVG_GRADE.SCORE >= 96 THEN 'S'
        WHEN AVG_GRADE.SCORE >= 90 THEN 'A'
        WHEN AVG_GRADE.SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN AVG_GRADE.SCORE >= 96 THEN E.SAL * 0.2
        WHEN AVG_GRADE.SCORE >= 90 THEN E.SAL * 0.15
        WHEN AVG_GRADE.SCORE >= 80 THEN E.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES E
JOIN (
    SELECT EMP_NO, AVG(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) AS AVG_GRADE
ON E.EMP_NO = AVG_GRADE.EMP_NO
ORDER BY E.EMP_NO;