SELECT 
    YEAR(E1.DIFFERENTIATION_DATE) AS YEAR, 
    E2.MAX_COLONY - E1.SIZE_OF_COLONY AS YEAR_DEV, 
    E1.ID
FROM ECOLI_DATA AS E1
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        MAX(SIZE_OF_COLONY) AS MAX_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS E2
ON YEAR(E1.DIFFERENTIATION_DATE) = E2.YEAR
ORDER BY YEAR, YEAR_DEV;
